services:
  front-end:
    build:
      context: ./Sport-See-FR_Front-End
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Sport-See-FR_Front-End:/Sport-See-FR

  back-end:
    build:
      context: ./Sport-See-FR_Back-End
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
